apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      id: wordpress
  template:
    metadata:
      labels:
        id: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: frontend-config
        - secretRef:
            name: frontend-secret