apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: frontend
data:
  WORDPRESS_DB_HOST: {{ .Values.frontend.config.WORDPRESS_DB_HOST }}
  WORDPRESS_DB_NAME: {{ .Values.frontend.config.WORDPRESS_DB_NAME }}