apiVersion: v1
kind: Secret
metadata:
    name: frontend-secret
    namespace: frontend
data:
    WORDPRESS_DB_USER: {{ .Values.frontend.secret.WORDPRESS_DB_USER }}
    WORDPRESS_DB_PASSWORD: {{ .Values.frontend.secret.WORDPRESS_DB_PASSWORD }}