apiVersion: apps/v1
kind: Deployment
metadata:
  name: px
  namespace: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      id: px
  template:
    metadata:
      labels:
        id: px
    spec:
      containers:
      - name: px
        image: gcr.io/psychic-etching-434700-b5/nginx:latest
        ports:
        - containerPort: 8080