apiVersion: v1
kind: Secret
metadata:
    name: backend-secret
    namespace: backend
data:
    # somewordpress
    MYSQL_ROOT_PASSWORD: {{ .Values.backend.secret.MYSQL_ROOT_PASSWORD }}
    MYSQL_DATABASE: {{ .Values.backend.secret.MYSQL_DATABASE }}
    MYSQL_USER: {{ .Values.backend.secret.MYSQL_USER }}
    MYSQL_PASSWORD: {{ .Values.backend.secret.MYSQL_PASSWORD }}